#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist "$DISPLAY" | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run -it \
    --rm \
    --volume="$(pwd):/home/wine/Apps" \
    --volume=$XSOCK:$XSOCK:rw \
    --volume=$XAUTH:$XAUTH:rw \
    --volume=wine:/home/wine \
    --env="XAUTHORITY=${XAUTH}" \
    --env="DISPLAY" \
    --user="wine" \
    --workdir=/home/wine/Apps \
    --net host \
    --name wine wine:latest "$@"
